//Security

//Creating the user
####
POST http://localhost:8080/signup HTTP/1.1
Content-Type: application/json

{
  "username": "john@smith.com",
  "password": "P@ssw0rd!",
  "first_name": "John",
  "last_name": "Smith",
  "roles": ["USER"]
}



// Generating token

// 
#####
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
  "username": "john@smith.com",
  "password": "P@ssw0rd!"
}
