//Security

####
POST http://localhost:8080/signup HTTP/1.1
Content-Type: application/json

{
  "username": "ariany0@yahoo.com",
  "firstName": "Rayane",
  "lastName": "Smith",
  "password": "P@ssw0rd!",
  "roles": ["USER"]
}


// 
#####
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
  "username": "john@smith.com",
  "password": "P@ssw0rd!",
  "first_name": "John",
  "last_name": "Smith"
}


#####
// Get transactions by user id
GET http://localhost:8080/api/vault/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC1zb2xhci1mYXJtIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjkyMzMzMTU5fQ.q3MvwNnXnxDJrd-STFYXZQ6cmK1CnSdtLFmAB7QUdX8
#####
GET http://localhost:8080/api/vault/transaction/2
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC1zb2xhci1mYXJtIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjkyMzMzMTU5fQ.q3MvwNnXnxDJrd-STFYXZQ6cmK1CnSdtLFmAB7QUdX8

####
GET http://localhost:8080/api/vault/transaction/goals/2
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC1zb2xhci1mYXJtIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjkyMzMzMTU5fQ.q3MvwNnXnxDJrd-STFYXZQ6cmK1CnSdtLFmAB7QUdX8
####
// Create an transaction
POST http://localhost:8080/api/vault/transaction/create HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC1zb2xhci1mYXJtIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjkyMzMzMTU5fQ.q3MvwNnXnxDJrd-STFYXZQ6cmK1CnSdtLFmAB7QUdX8
{
  "appUserId": 1,
  "goalsId": 2,
  "description": "Travel to Iceland",
  "amount": 2000,
  "transactionDate": "2023-08-15"
}


####
//Update an transaction

PUT http://localhost:8080/api/vault/transaction/2 HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC1zb2xhci1mYXJtIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjkyMzA4NjcxfQ.zauDxj3_xX77XATadj7D3jWAyP6osMStFpNMuOPfAcw

{
  "transactionId": 2,
  "appUserId": 1,
  "goalsId": 1,
  "description": "Cat Food",
  "amount": 75,
  "transactionDate": "2023-07-15"
}


####
//Delete a transaction

DELETE http://localhost:8080/api/vault/transaction/5 HTTP/1.1
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC1zb2xhci1mYXJtIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjkyMzA4NjcxfQ.zauDxj3_xX77XATadj7D3jWAyP6osMStFpNMuOPfAcw


#########

GET http://localhost:8080/api/vault/budgetcategory/spending
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC1zb2xhci1mYXJtIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjkyMzM1NzgxfQ.GK4WDQrn4-Q9kTzuNINQag__MCujuIzMvRv93vYvZps


