//Security

####
POST http://localhost:8080/signup HTTP/1.1
Content-Type: application/json

{
  "username": "ariany@yahoo.com",
  "password": "P@ssw0rd!",
  "roles": ["USER"]
}


// 
#####
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
  "username": "john@smith.com",
  "password": "P@ssw0rd!"
}


#####
// Get transactions by user id
GET http://localhost:8080/api/vault/personal
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC1zb2xhci1mYXJtIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjkyMjE5NjMyfQ.kso79mNH4YqQ3bbwhUvkEAW6C9ve_TJoVFcXCXQoYxc


###
GET http://localhost:8080/api/vault/transaction/2
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC1zb2xhci1mYXJtIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjkyMjE5NjMyfQ.kso79mNH4YqQ3bbwhUvkEAW6C9ve_TJoVFcXCXQoYxc

####
GET http://localhost:8080/api/vault/transaction/goals/1
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC1zb2xhci1mYXJtIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjkyMjE5NjMyfQ.kso79mNH4YqQ3bbwhUvkEAW6C9ve_TJoVFcXCXQoYxc

####
// Create an transaction
POST http://localhost:8080/api/vault HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC1zb2xhci1mYXJtIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjkyMjE5NjMyfQ.kso79mNH4YqQ3bbwhUvkEAW6C9ve_TJoVFcXCXQoYxc

{
  "appUserId": 1,
  "goalsId": 1,
  "description": "Rent",
  "amount": 5,
  "transactionDate": "2023-08-15"
}


####
//Update an transaction

PUT http://localhost:8080/api/vault/2 HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC1zb2xhci1mYXJtIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjkyMjE5NjMyfQ.kso79mNH4YqQ3bbwhUvkEAW6C9ve_TJoVFcXCXQoYxc

{
  "transactionId": 2,
  "appUserId": 1,
  "goalsId": 1,
  "description": "Snake Food",
  "amount": 75,
  "transactionDate": "2023-07-15"
}


####
//Delete a transaction

DELETE http://localhost:8080/api/vault/6 HTTP/1.1
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC1zb2xhci1mYXJtIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjkyMjE5MTI4fQ.SAdBvmJvyliiuosXnX1SSfC_mJ1_kWt6lkdV7HBOAu4